### ISSUE TITLE
Loop on youtube not working

### ISSUE THREAD

**Issue by delmicio** [OriginalEXE/vidim#1]
Windows 10
Chrome

Where? https://originalexe.github.io/vidim/#docs

**Comment by delmicio** [comment]
adding `&loop=1&playlist=VIDEOID` is a quick fix, but not as smooth as it should be

**Comment by delmicio** [comment]
I've send a PR #2 to fix this. Was already there but not in the url params.

**Comment by delmicio** [comment]
It doesn't fix the problem, after the end of the video it stuck with the loading spinner.

**Comment by OriginalEXE** [comment]
Hi,

thank you for reporting this issue. I can reproduce the problem here. Taking a look.

**Comment by OriginalEXE** [comment]
Hi,

can you please try the latest version in the develop branch and let me know if that works on your side: https://raw.githubusercontent.com/OriginalEXE/vidim/develop/dist/vidim.min.js

**Comment by delmicio** [comment]
@OriginalEXE It's working perfect now! Thanks you very much.

**Comment by OriginalEXE** [comment]
Awesome, thank you for confirming, I'll release the new version soon with the fix.

**Comment by OriginalEXE** [comment]
Fixed in 1.0.1
