### ISSUE TITLE
Back to page with video loop not working

### ISSUE THREAD

**Issue by delmicio** [OriginalEXE/vidim#3]
Hi,
When I go to my site with a youtube video loop It works, but If I leave that window/tab and then come back it doesn't work anymore, it stays with the youtube loading spinner.

On chrome with windows 10.

**Comment by OriginalEXE** [comment]
Hi,

thank you for reporting this. I think this is happening because browsers throttle the `setTimeout` for windows that lose focus. Let me try finding a smart way of overcoming that, will update you when I have a fix.

**Comment by OriginalEXE** [comment]
Hi, apologies for the delay.

Can you please try the new version, it should solve the issue which you reported: https://raw.githubusercontent.com/OriginalEXE/vidim/develop/dist/vidim.min.js

**Comment by delmicio** [comment]
Yes, It's working perfectly!

**Comment by OriginalEXE** [comment]
Published v1.0.1 to npm, thanks again for reporting this :)
